config/routes.rb
Depot::Application.routes.draw do

  
  scope '(:locale)' do
    get "user_cart/show_user_cart"
    get 'admin' => 'admin#index'
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end 
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :comments
    resources :categories
    resources :parent_categories
    resources :products do
      get :who_bought, on: :member
    end 
    root to: 'store#index', as: 'store'
    post '/' => 'store#index'
    post '/store/show' => 'store#show'
    post '/store/search' => 'store#search'
    get '/orders/ship/:id' => 'orders#ship', as: :orders_ship
    get '/products/add_like/:id' => 'products#add_like', as: :products_add_like
    get '/orders/user_orders/:id' => 'orders#user_orders', as: :orders_user_orders
  end

  

  

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :user
  
  accepts_nested_attributes_for :line_items
  
  attr_accessible :line_items_attributes
  
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_category_id
  
  has_many :products
  belongs_to :parent_category
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :product_id
  
  validates :content, :user_id, :product_id, presence:true
  
  belongs_to :product
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  attr_accessible :cart_id, :product_id, :quantity, :product
  
  validates :quantity, numericality: {greater_than_or_equal_to: 1}
  
  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :name, :address, :email, :pay_type, :status, :user_id
  
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  
  has_many :line_items, dependent: :destroy
  belongs_to :user
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/parent_category.rb
class ParentCategory < ActiveRecord::Base
  attr_accessible :name
  
  has_many :categories
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :description, :image_url, presence:true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'must be a URL for GIF, JPG or PNG image.' 
  }
  
  has_many :line_items
  has_many :orders, through: :line_items
  has_many :comments, dependent: :destroy
  before_destroy :ensure_not_referenced_by_any_line_item
  belongs_to :category
  
  accepts_nested_attributes_for :category
  
  attr_accessible :title, :description, :image_url, :price, :category_id, :like_num
  
  def self.search(search)
    if search
      where('title like ?', "%#{search}%")
    else
      all
    end
  end
  
  private
  
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  
  attr_accessible :name, :password_digest, :password, :password_confirmation, :permission
  validates :name, presence: true, uniqueness: true
  has_secure_password
  
  has_one :cart, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def set_user_cart(current_cart)
    cart = current_cart
  end
  
  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_filter :authorize
  
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to :back }
        format.json { head :no_content }
        format.js { @user_cart = current_cart }
      else
        format.html { redirect_to :back }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
        format.js { @user_cart = current_cart
                    @error = @cart.errors }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
      format.js { @user_cart = current_cart }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user_cart_helper.rb
module UserCartHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_cart.html.erb
<div class="well">
	<div class="cart_title">
		<h2><%= t('.title') %></h2>
	</div>
	<table class="table table-striped table-hover">
		<%= render(cart.line_items)  %>

		<tr class="total_line">
			<td colspan="2">Total</td>
			<td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
		</tr>
	</table>

	<%= button_to t('.view_cart'), user_cart_show_user_cart_path, method: :get, class: "btn btn-primary" %>
	<%= button_to t('.empty'), 
				  cart,
				  confirm: 'Are you sure?',
				  method: :delete,
				  class: "btn btn-danger",
				  remote: true %>
</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
$('#user_cart').html("<%= j render partial: 'user_cart/user_cart', locals: {user_cart: @user_cart} %>");

$('#cart').hide('blind',1000);

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice">
	<%= notice %>
</p>
<% end %>

<div class="cart_title">Your Cart</div>
<table>
	<%= render(@cart.line_items)  %>
		
	<tr class="total_line">
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
	</tr>	
</table>

<%= button_to 'Empty cart', @cart,
							confirm: 'Are you sure?', 
							method: :delete %>

app/views/carts/update.js.erb
<% if @error %>
	$('.alert').css('display', 'block')
<% else %>
	$('.alert').css('display', 'none')
<% end %>


$('#user_cart').flip({
	direction: 'lr',
	color: 'transparent'
})

$('#user_cart').html("<%= j render partial: 'user_cart/user_cart', locals: {user_cart: @user_cart} %>");