config/routes.rb
Depot::Application.routes.draw do

  
  scope '(:locale)' do
    get "user_cart/show_user_cart"
    get 'admin' => 'admin#index'
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end 
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :comments
    resources :categories
    resources :parent_categories
    resources :products do
      get :who_bought, on: :member
    end 
    root to: 'store#index', as: 'store'
    post '/' => 'store#index'
    post '/store/show' => 'store#show'
    post '/store/search' => 'store#search'
    get '/orders/ship/:id' => 'orders#ship', as: :orders_ship
    get '/products/add_like/:id' => 'products#add_like', as: :products_add_like
    get '/orders/user_orders/:id' => 'orders#user_orders', as: :orders_user_orders
  end

  

  

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :user
  
  accepts_nested_attributes_for :line_items
  
  attr_accessible :line_items_attributes
  
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_category_id
  
  has_many :products
  belongs_to :parent_category
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :product_id
  
  validates :content, :user_id, :product_id, presence:true
  
  belongs_to :product
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  attr_accessible :cart_id, :product_id, :quantity, :product
  
  validates :quantity, numericality: {greater_than_or_equal_to: 1}
  
  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :name, :address, :email, :pay_type, :status, :user_id
  
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  
  has_many :line_items, dependent: :destroy
  belongs_to :user
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/parent_category.rb
class ParentCategory < ActiveRecord::Base
  attr_accessible :name
  
  has_many :categories
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :description, :image_url, presence:true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'must be a URL for GIF, JPG or PNG image.' 
  }
  
  has_many :line_items
  has_many :orders, through: :line_items
  has_many :comments, dependent: :destroy
  before_destroy :ensure_not_referenced_by_any_line_item
  belongs_to :category
  
  accepts_nested_attributes_for :category
  
  attr_accessible :title, :description, :image_url, :price, :category_id, :like_num
  
  def self.search(search)
    if search
      where('title like ?', "%#{search}%")
    else
      all
    end
  end
  
  private
  
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  
  attr_accessible :name, :password_digest, :password, :password_confirmation, :permission
  validates :name, presence: true, uniqueness: true
  has_secure_password
  
  has_one :cart, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def set_user_cart(current_cart)
    cart = current_cart
  end
  
  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_filter :authorize
  
  def index
    @total_orders = Order.count
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :authorize, only: [:add_like]
  before_action :set_product, only: [:show, :edit, :update, :destroy, :add_like]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.all
    @products = Product.paginate page: params[:page], order: 'created_at desc', per_page: 5
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.image_url = upload

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
  
  def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
      format.atom
    end
  end
  
  def upload
    uploaded_io = params[:product][:image]
    if uploaded_io == nil
      return 'default.jpg'
    end
    File.open(Rails.root.join('app/assets', 'images', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    uploaded_io.original_filename
  end
  
  def add_like
    @product.like_num += 1
    respond_to do |format|
      if @product.save
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category_id, :image)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/user_cart_helper.rb
module UserCartHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/products/_form.html.erb
<div class="form-horizontal well">
	<fieldset>
		<legend>
			Please enter book info
		</legend>
		
		<%= form_for @product, html: { multipart: true } do |f| %>
		<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

			<ul>
				<% @product.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="control-group">
			<%= f.label :title, class: "control-label" %>
			<div class="controls">
				<%= f.text_field :title, class: "input-xlarge" %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :description, class: "control-label" %>
			<div class="controls">
				<%= f.text_area :description, rows: 6, class: "input-xlarge" %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :image, class: "control-label" %>
			<div class="controls">
				<%= f.file_field :image, class: "input-xlarge", accept: "image/gif, image/jpeg, image/png" %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :price, class: "control-label" %>
			<div class="controls">
				<%= f.text_field :price, class: "input-xlarge" %>
			</div>
		</div>

		<div class="control-group">
			<%= f.label :category, class: "control-label" %>
			<div class="controls">
				<%= f.collection_select :category_id, Category.all, :id, :name %>
			</div>
		</div>

		<div class="actions form-actions">
			<%= f.submit class: "btn btn-primary" %>
		</div>
		<% end %>
		
	</fieldset>
</div>

app/views/products/_product.html.erb
<div id="entry<%= product.id%>" class="entry bsa well">
	<%= image_tag(product.image_url, class: "thumbnail book_img") %>
	<h3 class="item_name"><%= product.title %></h3>
	
	<p>
		<%= sanitize(product.description) %>
	</p>
	<div class="price_line">
		<span class="price"><%= number_to_currency(product.price) %></span>
		<a href="/products/add_like/<%= product.id %>" class="like_btn btn btn-primary pull-right" data-remote="true" style="margin-left:10px;">
			<i class="icon-heart icon-white"></i>
			<%= t('.like') %>(<%= product.like_num %>)
		</a>
		<a href="#modal<%= product.id %>" class="btn btn-primary comment_btn pull-right" data-toggle="modal" style="margin-left:10px;">
			<%= t('.comment') %>
		</a>
		<%= button_to t('.add_html'),
					  line_items_path(product_id: product),
					  remote: true,
					  class: "btn btn-primary add_btn pull-right" %>
	</div>
</div>

<div id="modal<%= product.id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			×
		</button>
		<h3 id="myModalLabel"><%= product.title %></h3>
		
	</div>
	<div class="modal-body">
		<%= render partial: 'comments/new_comment', locals: { product_id: product.id } %>
		<hr>
		<div class="all_comments" >
			<h5> Total <%= product.comments.length %> comments: </h5>
			<%= render product.comments.order('created_at desc') %>
		</div>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">
			<%= t('.close_modal') %>
		</button>
	</div>
</div>

app/views/products/add_like.js.erb
$('#entry<%= @product.id %> .like_btn').html("<i class='icon-heart icon-white'></i><%= j t('.like') %>(<%= @product.like_num %>)")

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1><%= t('.page_title') %></h1>
<p class="lead"><%= t('.page_subtitle') %> <%= link_to t('.new_product'), new_product_path, class: "btn btn-primary" %></p>

<table class="blur">
<% @products.each do |product| %>
	<tr>
		
		<td class="span2">
			<%= image_tag(product.image_url, class: 'list_image thumbnail')%>
		</td>
		
		<td class="list_description">
			<dl>
				<dt><%= product.title %></dt>
				<dd><%= truncate(strip_tags(product.description), length: 250)%></dd>
			</dl>
		</td>
		
		<td class="list_actions span2">
			<p><%= link_to t('.show'), product_path(product), class: "btn " %></p>
			<p><%= link_to t('.edit'), edit_product_path(product), class: "btn" %></p>
			<p><%= link_to t('.dele'), product,
								confirm: 'Are you sure?',
								method: :delete,
								class: "btn btn-danger" %>
			</p>
		</td>
	</tr>
<% end %>
</table>

<div>
	<%= will_paginate @products, renderer: BootstrapPagination::Rails %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% if notice %>
<p id="notice" class="alert alert-info">
	<%= notice %>
</p>
<% end %>

<h1>Book Information</h1>

<div id="book_info">
	<%= render @product %>
</div>

<div id="book_comments" class="well" style="overflow: hidden">
	<h4> Total <%= @product.comments.length %> comments: </h4>
	<%= render @product.comments.order('created_at desc') %>
</div>

<%= link_to 'Edit', edit_product_path(@product), class: "btn btn-primary", style: "margin-bottom:10px; margin-right: 10px" %>
<%= link_to 'Back', products_path, class: "btn btn-primary", style: "margin-bottom:10px;" %>